apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
    - name: image-reference
      default: "zot-service.cluster-services.svc.cluster.local:5000/my-app:latest"
    - name: dockerfile-path
      default: "Dockerfile"
    - name: build-context
      default: "."
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params:repo-url)
    - name: build-push
      runAfter: ["fetch-repo"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params:image-reference)
        - name: DOCKERFILE
          value: $(params.dockerfile-path)
        - name: CONTEXT
          value: $(params.build-context)
        # Add --insecure because Zot doesn't use TLS
        - name: EXTRA_ARGS
          value: ["--skip-tls-verify", "--insecure", "--insecure-pull"]
