apiVersion: apps/v1
kind: Deployment
metadata:
  name: orb-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orb-frontend
  template:
    metadata:
      labels:
        app: orb-frontend
    spec:
      containers:
      - name: orb-frontend
        image: 192.168.1.196:30500/orb-of-pondering-frontend:1766258883-1ace7c2 # {"$imagepolicy": "flux-system:pondering-policy-frontend"}
        ports:
        - containerPort: 2222
---
apiVersion: v1
kind: Service
metadata:
  name: orb-frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: orb-frontend
  ports:
    - protocol: TCP
      port: 2222 # Port the service exposes internally
      targetPort: 2222 # Port the container is listening on
      nodePort: 30502 # Port exposed on all cluster nodes
