apiVersion: apps/v1
kind: Deployment
metadata:
  name: orb-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orb-backend
  template:
    metadata:
      labels:
        app: orb-backend
    spec:
      containers:
      - name: orb-backend
        image: 192.168.1.196:30500/orb-of-pondering-backend:1766461659-f2eba25 # {"$imagepolicy": "flux-system:pondering-policy-backend"}
        ports:
        - containerPort: 8000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key # The name of the Secret
              key: api-key # The key inside the Secret
---
apiVersion: v1
kind: Service
metadata:
  name: orb-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: orb-backend
  ports:
    - protocol: TCP
      port: 8000 # Port the service exposes internally
      targetPort: 8000 # Port the container is listening on
      nodePort: 30501 # Port exposed on all cluster nodes
