apiVersion: apps/v1
kind: Deployment
metadata:
  name: annoying-noises
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annoying-noises
  template:
    metadata:
      labels:
        app: annoying-noises
    spec:
      containers:
      - name: annoying-noises
        image: 192.168.1.196:30500/discord-dota:1768758656-73a0719 # {"$imagepolicy": "flux-system:annoying-noises-policy"}
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: annoying-noises-secret
              key: DISCORD_TOKEN
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/mapping.json
          subPath: mapping.json
      volumes:
      - name: config-volume
        configMap:
          name: annoying-noises-config
---
apiVersion: v1
kind: Service
metadata:
  name: annoying-noises-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: annoying-noises
  ports:
    - protocol: TCP
      port: 3000 # Port the service exposes internally
      targetPort: 3000 # Port the container is listening on
      nodePort: 30504 # Port exposed on all cluster nodes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: annoying-noises-config
  namespace: default
data:
  mapping.json: |
    [
      {
        "event": "player.deaths",
        "sound": "https://www.myinstants.com/media/sounds/oh-brother-this-guy-stinks.mp3",
        "condition": ">",
        "value": 0
      },
      {
        "event": "player.kills",
        "sound": "https://www.myinstants.com/media/sounds/anime-wow-sound-effect.mp3",
        "condition": "===",
        "value": 1
      },
      {
        "event": "player.kills",
        "sound": "https://www.myinstants.com/media/sounds/anime-ahh.mp3",
        "condition": ">",
        "value": 1
      }
    ]
