apiVersion: apps/v1
kind: Deployment
metadata:
  name: annoying-noises
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annoying-noises
  template:
    metadata:
      labels:
        app: annoying-noises
    spec:
      securityContext:
        fsGroup: 1000 # Automatically makes volumes writable by group 1000
      initContainers:
      - name: init-settings # 
        image: busybox
        command:
        - 'sh'
        - '-c'
        - |
          if [ -d /mnt/settings.json ]; then rm -rf /mnt/settings.json; fi
          if [ ! -f /mnt/settings.json ]; then echo "{}" > /mnt/settings.json; fi
          if [ ! -f /mnt/mapping.json ]; then echo "[]" > /mnt/mapping.json; fi

          chmod 664 /mnt/settings.json /mnt/mapping.json
          chown 1000:1000 /mnt/settings.json /mnt/mapping.json
        volumeMounts:
        - name: settings-volume
          mountPath: /mnt
      containers:
      - name: annoying-noises
        image: 192.168.1.196:30500/discord-dota:1787075407-a6c69cc # {"$imagepolicy": "flux-system:annoying-noises-policy"}
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: https://otelcollectorhttp.explosivejuice.com
        - name: CLICKHOUSE_HOST
          value: http://clickhouse-service.cluster-services.svc.cluster.local:8123
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: annoying-noises-secret
              key: DISCORD_TOKEN
        volumeMounts:
        - name: settings-volume
          mountPath: /usr/src/app/settings.json
          subPath: settings.json
        - name: settings-volume
          mountPath: /usr/src/app/mapping.json
          subPath: mapping.json
        - name: sounds-volume
          mountPath: /usr/src/app/sounds
        resources:
          limits:
            memory: "1Gi"
      volumes:
      - name: settings-volume
        persistentVolumeClaim:
          claimName: annoying-noises-settings
      - name: sounds-volume
        persistentVolumeClaim:
          claimName: annoying-noises-sounds
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: annoying-noises-sounds
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: annoying-noises-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: annoying-noises
  ports:
    - protocol: TCP
      port: 3000 # Port the service exposes internally
      targetPort: 3000 # Port the container is listening on
      nodePort: 30504 # Port exposed on all cluster nodes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: annoying-noises-settings
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
