apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrepo
      value: $(body.repository.url)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  namespace: tekton-pipelines
  name: git-template
spec:
  params:
    - name: gitrepo
      description: "The URL of the git repo from the webhook"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-push-run-
      spec:
        pipelineRef:
          name: build-and-push-pipeline
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes: [ReadWriteOnce]
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: repo-url
            value: $(tt.params.gitrepo)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: git-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-trigger-sa
  triggers:
    - bindings:
        - ref: git-binding
      template:
        ref: git-template
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-trigger-sa
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-trigger-cluster-role
  namespace: tekton-pipelines
rules:
  # Permissions to create PipelineRuns in the namespace
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelines"]
    verbs: ["create", "get", "list"]
  # Permissions for the Listener to manage itself and triggers
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "clusterinterceptors", "clustertriggerbindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-trigger-cluster-binding
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-trigger-sa
    namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-trigger-cluster-role
