apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrepo
      value: $(body.repository.url)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  namespace: tekton-pipelines
  name: git-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-push-run-
      spec:
        pipelineRef:
          name: build-and-push-pipeline
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes: [ReadWriteOnce]
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: repo-url
            value: $(tt.params.gitrepo)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: git-listener
  namespace: tekton-pipelines
spec:
  triggers:
    - bindingRef:
        name: git-binding
      templateRef:
        name: git-template
