apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soft-serve-pvc
  namespace: cluster-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-serve
  namespace: cluster-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soft-serve
  template:
    metadata:
      labels:
        app: soft-serve
    spec:
      containers:
        - name: soft-serve
          image: charmcli/soft-serve:latest
          ports:
            - containerPort: 23231 # SSH
            - containerPort: 9418  # Git
            - containerPort: 8080  # HTTP
          env:
            - name: SOFT_SERVE_DATA_PATH
              value: "/data"
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: soft-serve-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: soft-serve-service
  namespace: cluster-services
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 23231
      targetPort: 23231
    - name: git
      port: 9418
      targetPort: 9418
  selector:
    app: soft-serve
